Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
states, emissions = nlgssm.sample(key=0, num_timesteps=100)


all_figures = {}
fig, ax = plt.subplots()
true_title = "Noisy obervations from hidden trajectory"
_ = plot_inference(states, emissions, ax=ax, title=true_title)
all_figures["ekf_spiral_true"] = fig
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [5], line 1[0m
[0;32m----> 1[0m states, emissions [38;5;241m=[39m [43mnlgssm[49m[38;5;241;43m.[39;49m[43msample[49m(key[38;5;241m=[39m[38;5;241m0[39m, num_timesteps[38;5;241m=[39m[38;5;241m100[39m)
[1;32m      4[0m all_figures [38;5;241m=[39m {}
[1;32m      5[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()

[0;31mAttributeError[0m: 'NLGSSMParams' object has no attribute 'sample'
AttributeError: 'NLGSSMParams' object has no attribute 'sample'

